version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    command: npm start
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:3001
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - frontend/.env
    networks:
      - app-network

networks:
  app-network:
